### ISSUE TITLE
[Bug]: prelaunch checklist

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/two-towers#33]
- [x] #122
- [x] #185
- [x] make repo public
- [x] verify all closed issues and add the "verified" label
- [x] switch to real domain with cloudflare variable in the [build command](https://developers.cloudflare.com/pages/framework-guides/deploy-a-hugo-site#deploy-with-cloudflare-pages)

**Comment by aaaaargZombies** [comment]
verifying resources are being served from appropriate urls in production and on previews

https://towersoldham.uk/

https://socialsharepreview.com/?url=https://towersoldham.uk
https://socialsharepreview.com/?url=https://3cdf57d4.raftt.pages.dev/

![2023-05-25-113943_1920x1080_scrot](https://github.com/geeksforsocialchange/two-towers/assets/6824891/2e505dee-006e-4466-9f32-ce423a9d4840)
![2023-05-25-113956_1920x1080_scrot](https://github.com/geeksforsocialchange/two-towers/assets/6824891/cbc26e24-4fb7-4d6f-8bdc-649313f7c23e)
