### ISSUE TITLE
Images display as cloud shaped

### ISSUE THREAD

**Issue by r-ferrier** [geeksforsocialchange/two-towers#37]
## User story

As a visitor I want to see the timeline as a flurry of little clouds & memories

## Acceptance criteria

- [ ] Timeline images display on the timeline as cloud shaped

## Implementation plan
- [ ] merge with images branch
- [ ] look at using clip mask with SVG outline
