### ISSUE TITLE
Add partner logos

### ISSUE THREAD

**Issue by aaaaargZombies** [geeksforsocialchange/two-towers#45]
## User story

Display partner images as per design of about page

## Acceptance criteria

- [x] partners must have an image
- [x] images should be resized to maximum display size
- [x] image must have alt-text
- [x] optional link to partners website

## Implementation notes & questions

The design layout is [here](https://xd.adobe.com/view/175f0048-4e15-46d2-9ffd-4c8a43c5be9e-420c/screen/a4db1487-c471-4297-b3c6-bccb3ff50029/)

## Implementation plan

- [ ] modify partners partial to have logo img tag
- [ ] put together partner data for FCHO, lottery, Oldham Coliseum
